on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: commitOrPullRequest
      id: commitOrPullRequest
      uses: actions/commitOrPullRequest@v1
